### ISSUE TITLE
Cannot authenticate with BWProject 

### ISSUE THREAD

**Issue by CheyRav1990** [BrandwatchLtd/bcr-api#18]
When trying to instantiate BWProject with username and project i receive:

13:50:59 DEBUG: https://api.brandwatch.com/projects

{"error":"unauthorized","error_description":"Invalid authentication credentials found on request"}

I have a bearer token in tokens.txt and I've tried the same bearer token manually via requests on my own environment and can access the project and queries so the token works. Might be an issue with the version of requests?
I'm currently using:

python - 3.7.6
requests - 2.22.0

**Comment by lululy** [comment]
I have the same issue here. I was wondering how you solve the issue.
