### ISSUE TITLE
1.3.1 on PyPI does not include rule validation fix

### ISSUE THREAD

**Issue by Miraliu** [BrandwatchLtd/bcr-api#20]
The fix in this commit https://github.com/BrandwatchLtd/bcr-api/commit/7aba3eb4e2e341c8d36c6d99fd44ba83658c75eb is not in the pypi package of 1.3.1, thus the rule validation function is broken. 
Can someone please republish it to pypi?

**Comment by pfairfax1** [comment]
Thanks for rasing this, I'm looking into it now

**Comment by pfairfax1** [comment]
Hi @Miraliu , this issue should now be resolved. I've tested and it seems fine to me. The latest version is now 1.3.2. Thanks again for raising :)
