### ISSUE TITLE
Cannot download past 30 pages, sometimes 26.

### ISSUE THREAD

**Issue by playfuldreamz** [BrandwatchLtd/bcr-api#22]
11:43:52 INFO: Mentions page 30 of queries Himelboim-COVID-19 Vaccine  retrieved
11:43:53 DEBUG: https://api.brandwatch.com/projects/1998295055/data/mentions/fulltext?queryId=2000452202&startDate=2021-01-17T05%3A00%3A00&endDate=2021-02-16T05%3A00%3A00&pageSize=5000&cursor=AQ%3DAA%3DAXd32J5I%3DMjAwMDQ1MjIwMiFmN2VmMGMxNTE4ZGIzMzQ1ZDE4MmIzNTRkMzRkM2JiZg
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-15-e687d212f179> in <module>
----> 1 filtered = queries.get_mentions(name = "Himelboim-COVID-19 Vaccine ",
      2                                 startDate = start,
      3                                 endDate = today)

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\bcr_api\bwdata.py in get_mentions(self, name, startDate, max_pages, **kwargs)
     34             key: value for (key, value) in kwargs.items() if key != "iter_by_page"
     35         }
---> 36         all_mentions = list(
     37             self.iter_mentions(
     38                 name=name,

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\bcr_api\bwdata.py in iter_mentions(self, name, startDate, max_pages, iter_by_page, **kwargs)
     78             else:
     79                 page_idx += 1
---> 80             next_cursor, next_mentions = self._get_mentions_page(params)
     81             if len(next_mentions) > 0:
     82                 cursor = next_cursor

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\bcr_api\bwdata.py in _get_mentions_page(self, params)
    994             raise KeyError("Mentions GET request failed", mentions)
    995 
--> 996         return mentions.get("nextCursor", None), mentions["results"]
    997 
    998     def _valid_input(self, param, setting):

KeyError: 'results'

**Comment by pfairfax1** [comment]
Hi @playfuldreamz, thanks for raising this. 

As this is not an official or supported Brandwatch library, it might be a little while before we can get around to having a look at this properly. However, I think there might be another way to get this data in the meantime. If you send me an email (peterf at brandwatch.com), with some info about what you're trying to do, I might be able to help

**Comment by ilbus** [comment]
Hi, I have seen similar issue and I am not sure for 100% but looks like API rate limit has been reach please doble check - https://developers.brandwatch.com/docs/best-practices#rate-limits
